CREATE TABLE IF NOT EXISTS files (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    path TEXT NOT NULL UNIQUE,
    size UNSIGNED BIG INT NOT NULL,
    uploaded DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    md5 TEXT NOT NULL,
    sha1 TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    sha512 TEXT NOT NULL,
    kind TEXT NOT NULL,
    parent TEXT NOT NULL AS (RTRIM(path, REPLACE(path, "/", ""))) STORED
);

CREATE TABLE IF NOT EXISTS deleted_files (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    path TEXT NOT NULL,
    size UNSIGNED BIG INT NOT NULL,
    uploaded DATETIME NOT NULL,
    deleted DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    md5 TEXT NOT NULL,
    sha1 TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    sha512 TEXT NOT NULL,
    kind TEXT NOT NULL,
    parent TEXT NOT NULL AS (RTRIM(path, REPLACE(path, "/", ""))) STORED
);

CREATE TABLE IF NOT EXISTS tokens (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    value TEXT NOT NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS token_paths (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    token INTEGER NOT NULL REFERENCES tokens(id),
    path TEXT NOT NULL,
    added DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    permission INT2 NOT NULL -- 0 = read, 1 = write, 2 = read/write
);

CREATE TABLE IF NOT EXISTS master_keys (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    value TEXT NOT NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_init BOOL NOT NULL DEFAULT FALSE
);
