CREATE TABLE IF NOT EXISTS files (
    id SERIAL NOT NULL PRIMARY KEY,
    path TEXT NOT NULL UNIQUE,
    size BIGINT NOT NULL,
    uploaded TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    md5 TEXT NOT NULL,
    sha1 TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    sha512 TEXT NOT NULL,
    kind TEXT NOT NULL,
    parent TEXT NOT NULL GENERATED ALWAYS AS (RTRIM(path, REPLACE(path, '/', ''))) STORED
);

CREATE TABLE IF NOT EXISTS deleted_files (
    id SERIAL NOT NULL PRIMARY KEY,
    path TEXT NOT NULL,
    size BIGINT NOT NULL,
    uploaded TIMESTAMP NOT NULL,
    deleted TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    md5 TEXT NOT NULL,
    sha1 TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    sha512 TEXT NOT NULL,
    kind TEXT NOT NULL,
    parent TEXT NOT NULL GENERATED ALWAYS AS (RTRIM(path, REPLACE(path, '/', ''))) STORED
);

CREATE TABLE IF NOT EXISTS tokens (
    id SERIAL NOT NULL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    value TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS token_paths (
    id SERIAL NOT NULL PRIMARY KEY,
    token INTEGER NOT NULL REFERENCES tokens(id),
    path TEXT NOT NULL,
    added TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    permission INT2 NOT NULL -- 0 = read, 1 = write, 2 = read/write
);

CREATE TABLE IF NOT EXISTS master_keys (
    id SERIAL NOT NULL PRIMARY KEY,
    value TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_init BOOL NOT NULL DEFAULT FALSE
);
